version: "3.7"

services:
  marklogic:
    image: marklogiccommunity/marklogic:9.0-8.2
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "8000-8002:8000-8002/tcp"
      - "8010-8011:8010-8011/tcp"
      - "8013:8013/tcp"
    expose:
      - "7997"
      - "7998"
      - "7999"

  ml-gradle:
    image: gradle:alpine
    depends_on:
      - "marklogic"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    working_dir: /usr/src/app
    command: "gradle -PmlHost=marklogic mlInit mlInstallAdmin --info"

volumes:
  marklogic_data: